### ISSUE TITLE
Events with item details in the data layer throw a tag firing exception: Firing Status Exception thrown

### ISSUE THREAD

**Issue by rusdragos** [stape-io/twitter-tag#4]
Tag Firing Status : Exception thrown
Happens when "Event Data" contains "Item Details" as shown in the image below. 

For example in a ecommerce store "Add to cart" or "Purchase" usually contains additional data about the products the user purchases. In this care it looks like the Twitter - Stape integration fails to fire the tag and the console log trows the error: "
TypeError: Can't set property contents of undefined."

Any ideas how to bypass the problem? Maybe you can adjust the conditions to only send the data that is matched with the format twitter requires, for example: Currency, price and ignore the rest of the details added in the Event Data->Item details. 

<img width="582" alt="items" src="https://user-images.githubusercontent.com/6596148/216790950-819f8b45-73b4-4d11-906b-a18748a5342c.png">

<img width="365" alt="error" src="https://user-images.githubusercontent.com/6596148/216791153-42dd1907-0411-404d-8f41-7e15d2ecf44d.png">

**Comment by Bukashk0zzz** [comment]
Thanks for the detailed issue. 
We will check and update our tag.

**Comment by Bukashk0zzz** [comment]
Thanks. We updated the Tag.
