### ISSUE TITLE
"Firebase settings" section to store OAuth access token?

### ISSUE THREAD

**Issue by alexgarciab** [stape-io/twitter-tag#8]
I see the tags of Google, Microsoft & Reddit have this section called "Firebase settings" to store the OAuth access token in Firestore.

Why the Twitter tag doesn't have such section (Firebase settings) and it includes the Oauth token & Oauth token secret directly in the general settings?

**Comment by Bukashk0zzz** [comment]
Twitter do not use oAuth 2 but different version more info https://developer.x.com/en/docs/twitter-ads-api/making-authenticated-requests
